apiVersion: apps/v1
kind: Deployment
metadata:
  name: okt8nrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okt8nrv
  template:
    metadata:
      labels:
        app: okt8nrv
    spec:
      containers:
      - image: okteto.dev/okt8nrv:latest
        name: okt8nrv
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: Vless_UUID
          value: "6b8239fc-adad-472a-89b3-059f9e5c3153"
        - name: Vless_Path
          value: "/6b8239fc-adad-472a-89b3-059f9e5c3153-vless"
        - name: Vmess_UUID
          value: "6b8239fc-adad-472a-89b3-059f9e5c3153"
        - name: Vmess_Path
          value: "/6b8239fc-adad-472a-89b3-059f9e5c3153-vmess"
        - name: Trojan_UUID
          value: "6b8239fc-adad-472a-89b3-059f9e5c3153"
        - name: Trojan_Path
          value: "/6b8239fc-adad-472a-89b3-059f9e5c3153-trojan"
        - name: SS_UUID
          value: "6b8239fc-adad-472a-89b3-059f9e5c3153"
        - name: SS_Path
          value: "/6b8239fc-adad-472a-89b3-059f9e5c3153-ss"
        - name: Share_Path
          value: "/6b8239fc-adad-472a-89b3-059f9e5c3153-share"
