apiVersion: v1
kind: Service
metadata:
  name: okt8nrv
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okt8nrv"
    port: 8080
  selector:
    app: okt8nrv
